blog/urls.py
from django.urls import pathfrom . import viewsapp_name = 'blog'urlpatterns = [    path('', views.home, name='blog_home'),    path('<int:blog_id>/', views.detail, name='detail'),]

personal_portfolio/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('portfolio.urls')),
    path('blog/', include('blog.urls')),
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

portfolio/urls.py
from django.urls import pathfrom . import viewsurlpatterns =[    path('', views.home, name='home')]

blog/models.py
from django.db import models

class Blog(models.Model):
    title = models.CharField(max_length=50)
    content = models.TextField()
    upload_date = models.DateField(auto_now=True)

    def __str__(self):
        return self.title

portfolio/models.py
from django.db import models

class Project(models.Model):
    title = models.CharField(max_length=50)
    description = models.CharField(max_length=255)
    image = models.ImageField(upload_to='portfolio/images/')
    url = models.URLField(blank=True)

    def __str__(self):
        return self.title

blog/views.py
from django.shortcuts import render, get_object_or_404
from .models import Blog

def home(request):
    blog_no = Blog.objects.count
    blogs = Blog.objects.order_by('-upload_date')[:6]
    return render(request, 'blog/blog_home.html', {'blogs': blogs, 'blog_no': blog_no})


def detail(request, blog_id):
    blog = get_object_or_404(Blog, pk=blog_id)
    return render(request, 'blog/detail.html', {'blog':blog})

portfolio/views.py
from django.shortcuts import render
from .models import Project

def home(request):
    projects = Project.objects.all()
    return render(request, 'portfolio/home.html', {'projects': projects})

templates/blog/blog_home.html
{% extends 'base.html' %}{% block content %}<div class="container">    <div style="text-align:center">        <div style="display:inline-block">            <h2 style="font-size:40px">Deeps has written {{blog_no}} blogs</h2>            <br>            <br>            <br>            <div class="row">                {% for blog in blogs %}                <div class="col">                    <div class="row row-cols-1 row-cols-md-2">                        <div class="col mb-4">                            <div class="card" style="width: 18rem;">                                <div class="card-body">                                    <h2 class="card-title">{{blog.title}}</h2>                                    <h4 class="card-title">{{ blog.upload_date}} uploaded</h4>                                    <p class="card-text">{{blog.content|striptags|truncatechars:245}}</p>                                    <a href="{% url 'blog:detail' blog.id %}" target="_blank" class="btn btn-danger">Go                                        To Blog</a>                                </div>                            </div>                        </div>                    </div>                </div>                {% endfor %}            </div>        </div>    </div></div>{% endblock %}

templates/blog/detail.html
{% extends 'base.html' %}{% block content %}<br><br><div class="container" style="text-align:center">    <h1 class="text-centre mt-5" style="font-size:100px">        {{ blog.title }}    </h1>    <h5 class="text-center text-muted mb-5" style="font-size:40px">        --{{blog.upload_date|date:'F jS Y'}}--    </h5></div><br><br><div class="container">    <p>        {{blog.content|safe}}    </p></div>{% endblock %}